### ISSUE TITLE
How to change Order Type

### ISSUE THREAD

**Issue by hoangxcg** [Abhisheksoni1/BitmexBot#3]
How to change order type of STOP_LOSS_FACTOR and STOP_PROFIT_FACTOR?
I want to change STOP_LOSS_FACTOR with **StopLimit** --> Stop Market **Stop**
and STOP_PROFIT_FACTOR with **Limit** --> Take Profit Market **MarketIfTouched**

**Comment by abhisheksoni-1** [comment]
the current code is for limit type orders this needs further development

**Comment by abhisheksoni-1** [comment]
anyone wants to work with me on this?
